AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/'
    - 'app/helpers/*.rb'

inherit_gem:
  rubocop-rails:
    - config/rails.yml

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout:
  EnforcedStyle: normal
